In [2]:
import tensorflow.compat.v1 as tf
import numpy as np

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

tf.disable_v2_behavior()
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))


logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))
                                  


Instructions for updating:
non-resource variables are not supported in the long term
0 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
1 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
2 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
3 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
4 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
5 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
6 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
7 7.6

92 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
93 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
94 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
95 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
96 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
97 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
98 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
99 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.34

176 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
177 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
178 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
179 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
180 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
181 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
182 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.01074422 -0.3438642 ]
 [ 1.5483537   0.8118616   0.10400692]]
183 7.6196823 [[-1.6195621   1.0356216   0.02359349]
 [ 1.8517162   0.010744

In [3]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = min_max_scaler(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]] #제일 마지막 한줄. 

tf.disable_v2_behavior()
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 1])
W = tf.Variable(tf.random_normal([4, 1]))
b = tf.Variable(tf.random_normal([1]))


hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                                         


0 Cost:  5.4855604 
Prediction:
 [[-2.456262  ]
 [-3.27488   ]
 [-2.042799  ]
 [-0.606573  ]
 [-1.4595433 ]
 [-1.2525846 ]
 [ 0.03034937]
 [ 0.01580018]]
1 Cost:  5.485198 
Prediction:
 [[-2.456149  ]
 [-3.2747717 ]
 [-2.0427094 ]
 [-0.60650533]
 [-1.4594617 ]
 [-1.252506  ]
 [ 0.03039938]
 [ 0.01584893]]
2 Cost:  5.4848375 
Prediction:
 [[-2.456036  ]
 [-3.2746634 ]
 [-2.0426204 ]
 [-0.6064377 ]
 [-1.4593804 ]
 [-1.2524276 ]
 [ 0.03044927]
 [ 0.01589775]]
3 Cost:  5.484476 
Prediction:
 [[-2.455923  ]
 [-3.2745547 ]
 [-2.042531  ]
 [-0.60637003]
 [-1.4592991 ]
 [-1.2523494 ]
 [ 0.03049922]
 [ 0.01594651]]
4 Cost:  5.4841146 
Prediction:
 [[-2.45581   ]
 [-3.2744465 ]
 [-2.0424418 ]
 [-0.6063024 ]
 [-1.4592177 ]
 [-1.2522708 ]
 [ 0.03054917]
 [ 0.01599532]]
5 Cost:  5.483753 
Prediction:
 [[-2.4556973 ]
 [-3.274338  ]
 [-2.0423524 ]
 [-0.6062346 ]
 [-1.459136  ]
 [-1.2521923 ]
 [ 0.03059906]
 [ 0.01604408]]
6 Cost:  5.4833927 
Prediction:
 [[-2.4555843 ]
 [-3.2742298 ]
 [-2.0422633 ]
 

 [ 0.02032995]]
94 Cost:  5.451688 
Prediction:
 [[-2.4456558 ]
 [-3.2647004 ]
 [-2.034418  ]
 [-0.60022086]
 [-1.4518995 ]
 [-1.2452233 ]
 [ 0.03503537]
 [ 0.02037859]]
95 Cost:  5.4513283 
Prediction:
 [[-2.445543  ]
 [-3.2645922 ]
 [-2.034329  ]
 [-0.6001535 ]
 [-1.4518185 ]
 [-1.2451451 ]
 [ 0.03508514]
 [ 0.02042717]]
96 Cost:  5.450969 
Prediction:
 [[-2.4454305 ]
 [-3.2644842 ]
 [-2.03424   ]
 [-0.6000859 ]
 [-1.4517372 ]
 [-1.2450669 ]
 [ 0.03513485]
 [ 0.0204758 ]]
97 Cost:  5.45061 
Prediction:
 [[-2.4453177 ]
 [-3.264376  ]
 [-2.0341508 ]
 [-0.60001856]
 [-1.4516559 ]
 [-1.2449884 ]
 [ 0.03518468]
 [ 0.02052438]]
98 Cost:  5.4502516 
Prediction:
 [[-2.4452052 ]
 [-3.264268  ]
 [-2.034062  ]
 [-0.59995097]
 [-1.4515748 ]
 [-1.2449107 ]
 [ 0.03523439]
 [ 0.02057302]]
99 Cost:  5.44989 
Prediction:
 [[-2.4450922 ]
 [-3.2641592 ]
 [-2.0339727 ]
 [-0.5998836 ]
 [-1.4514937 ]
 [-1.244832  ]
 [ 0.03528416]
 [ 0.0206216 ]]
100 Cost:  5.4495335 
Prediction:
 [[-2.44498   ]
 [-3.26405

164 Cost:  5.4266114 
Prediction:
 [[-2.437781 ]
 [-3.257139 ]
 [-2.0281937]
 [-0.5955052]
 [-1.446224 ]
 [-1.2397573]
 [ 0.0385142]
 [ 0.0237785]]
165 Cost:  5.4262543 
Prediction:
 [[-2.4376688 ]
 [-3.257031  ]
 [-2.0281053 ]
 [-0.5954378 ]
 [-1.4461432 ]
 [-1.2396793 ]
 [ 0.03856373]
 [ 0.0238269 ]]
166 Cost:  5.4258976 
Prediction:
 [[-2.4375565 ]
 [-3.2569234 ]
 [-2.0280163 ]
 [-0.5953707 ]
 [-1.4460623 ]
 [-1.2396014 ]
 [ 0.03861338]
 [ 0.02387536]]
167 Cost:  5.425541 
Prediction:
 [[-2.4374442 ]
 [-3.256816  ]
 [-2.0279279 ]
 [-0.5953035 ]
 [-1.4459815 ]
 [-1.2395234 ]
 [ 0.03866291]
 [ 0.02392375]]
168 Cost:  5.4251833 
Prediction:
 [[-2.437332  ]
 [-3.256708  ]
 [-2.027839  ]
 [-0.59523624]
 [-1.4459004 ]
 [-1.2394454 ]
 [ 0.03871244]
 [ 0.02397215]]
169 Cost:  5.4248266 
Prediction:
 [[-2.4372196 ]
 [-3.2566004 ]
 [-2.0277503 ]
 [-0.595169  ]
 [-1.4458194 ]
 [-1.2393677 ]
 [ 0.03876203]
 [ 0.02402061]]
170 Cost:  5.42447 
Prediction:
 [[-2.4371073 ]
 [-3.2564924 ]
 [-2.02766

259 Cost:  5.3927956 
Prediction:
 [[-2.427124  ]
 [-3.2469134 ]
 [-2.0197756 ]
 [-0.5891256 ]
 [-1.4385467 ]
 [-1.2323637 ]
 [ 0.04321843]
 [ 0.02837342]]
260 Cost:  5.3924413 
Prediction:
 [[-2.4270122 ]
 [-3.246806  ]
 [-2.0196872 ]
 [-0.5890587 ]
 [-1.4384658 ]
 [-1.2322857 ]
 [ 0.04326779]
 [ 0.0284217 ]]
261 Cost:  5.3920865 
Prediction:
 [[-2.4269001 ]
 [-3.2466981 ]
 [-2.0195987 ]
 [-0.5889916 ]
 [-1.4383852 ]
 [-1.2322083 ]
 [ 0.04331726]
 [ 0.02846998]]
262 Cost:  5.3917317 
Prediction:
 [[-2.426788  ]
 [-3.246591  ]
 [-2.0195103 ]
 [-0.58892447]
 [-1.4383044 ]
 [-1.2321303 ]
 [ 0.04336667]
 [ 0.02851826]]
263 Cost:  5.3913765 
Prediction:
 [[-2.4266763 ]
 [-3.2464833 ]
 [-2.0194218 ]
 [-0.5888576 ]
 [-1.4382238 ]
 [-1.2320528 ]
 [ 0.04341608]
 [ 0.02856654]]
264 Cost:  5.3910217 
Prediction:
 [[-2.4265642 ]
 [-3.2463758 ]
 [-2.0193331 ]
 [-0.5887905 ]
 [-1.438143  ]
 [-1.2319751 ]
 [ 0.04346555]
 [ 0.02861488]]
265 Cost:  5.390668 
Prediction:
 [[-2.4264524 ]
 [-3.2462685 ]


333 Cost:  5.366626 
Prediction:
 [[-2.4188528 ]
 [-3.2389722 ]
 [-2.0132394 ]
 [-0.58417356]
 [-1.4325861 ]
 [-1.2266234 ]
 [ 0.04687065]
 [ 0.03194261]]
334 Cost:  5.366273 
Prediction:
 [[-2.4187412 ]
 [-3.238865  ]
 [-2.0131512 ]
 [-0.5841067 ]
 [-1.4325057 ]
 [-1.2265459 ]
 [ 0.04691988]
 [ 0.03199077]]
335 Cost:  5.36592 
Prediction:
 [[-2.4186296 ]
 [-3.2387576 ]
 [-2.013063  ]
 [-0.5840398 ]
 [-1.4324254 ]
 [-1.2264684 ]
 [ 0.04696923]
 [ 0.03203899]]
336 Cost:  5.365567 
Prediction:
 [[-2.4185176 ]
 [-3.2386508 ]
 [-2.0129747 ]
 [-0.58397305]
 [-1.4323448 ]
 [-1.226391  ]
 [ 0.04701853]
 [ 0.03208715]]
337 Cost:  5.3652143 
Prediction:
 [[-2.418406  ]
 [-3.238543  ]
 [-2.0128865 ]
 [-0.58390605]
 [-1.4322642 ]
 [-1.2263135 ]
 [ 0.04706782]
 [ 0.03213525]]
338 Cost:  5.3648615 
Prediction:
 [[-2.4182944 ]
 [-3.2384357 ]
 [-2.0127983 ]
 [-0.5838393 ]
 [-1.4321839 ]
 [-1.226236  ]
 [ 0.04711711]
 [ 0.03218347]]
339 Cost:  5.364509 
Prediction:
 [[-2.4181828 ]
 [-3.238329  ]
 [-2.

405 Cost:  5.3412967 
Prediction:
 [[-2.4108224 ]
 [-3.2312665 ]
 [-2.0068965 ]
 [-0.57936776]
 [-1.4268016 ]
 [-1.2210528 ]
 [ 0.05041361]
 [ 0.03540349]]
406 Cost:  5.3409467 
Prediction:
 [[-2.410711  ]
 [-3.2311594 ]
 [-2.0068085 ]
 [-0.5793011 ]
 [-1.4267213 ]
 [-1.2209756 ]
 [ 0.05046272]
 [ 0.03545141]]
407 Cost:  5.340596 
Prediction:
 [[-2.4105997 ]
 [-3.2310529 ]
 [-2.0067205 ]
 [-0.5792345 ]
 [-1.4266411 ]
 [-1.2208983 ]
 [ 0.05051184]
 [ 0.03549939]]
408 Cost:  5.3402443 
Prediction:
 [[-2.4104881 ]
 [-3.2309456 ]
 [-2.0066326 ]
 [-0.57916784]
 [-1.4265609 ]
 [-1.2208211 ]
 [ 0.05056101]
 [ 0.03554744]]
409 Cost:  5.3398943 
Prediction:
 [[-2.410377  ]
 [-3.2308388 ]
 [-2.0065446 ]
 [-0.5791012 ]
 [-1.4264809 ]
 [-1.2207438 ]
 [ 0.05061007]
 [ 0.03559542]]
410 Cost:  5.339544 
Prediction:
 [[-2.4102657 ]
 [-3.2307322 ]
 [-2.0064569 ]
 [-0.57903457]
 [-1.4264007 ]
 [-1.2206666 ]
 [ 0.05065918]
 [ 0.03564334]]
411 Cost:  5.3391933 
Prediction:
 [[-2.4101543 ]
 [-3.2306256 ]
 

473 Cost:  5.31751 
Prediction:
 [[-2.4032617 ]
 [-3.22401   ]
 [-2.0009236 ]
 [-0.57484245]
 [-1.4213547 ]
 [-1.2158076 ]
 [ 0.05375004]
 [ 0.03866315]]
474 Cost:  5.317161 
Prediction:
 [[-2.4031506 ]
 [-3.2239032 ]
 [-2.000836  ]
 [-0.57477593]
 [-1.4212748 ]
 [-1.2157305 ]
 [ 0.05379903]
 [ 0.03871101]]
475 Cost:  5.3168125 
Prediction:
 [[-2.4030395 ]
 [-3.2237968 ]
 [-2.0007482 ]
 [-0.57470953]
 [-1.4211949 ]
 [-1.2156535 ]
 [ 0.05384803]
 [ 0.03875881]]
476 Cost:  5.3164635 
Prediction:
 [[-2.4029284 ]
 [-3.22369   ]
 [-2.0006604 ]
 [-0.574643  ]
 [-1.4211148 ]
 [-1.2155763 ]
 [ 0.05389702]
 [ 0.03880674]]
477 Cost:  5.3161144 
Prediction:
 [[-2.4028172 ]
 [-3.2235837 ]
 [-2.0005727 ]
 [-0.5745765 ]
 [-1.4210349 ]
 [-1.2154993 ]
 [ 0.05394602]
 [ 0.0388546 ]]
478 Cost:  5.3157654 
Prediction:
 [[-2.4027061 ]
 [-3.223477  ]
 [-2.000485  ]
 [-0.5745101 ]
 [-1.4209548 ]
 [-1.2154223 ]
 [ 0.05399495]
 [ 0.0389024 ]]
479 Cost:  5.3154173 
Prediction:
 [[-2.4025955 ]
 [-3.2233706 ]
 [

555 Cost:  5.2889767 
Prediction:
 [[-2.3941665 ]
 [-3.2152796 ]
 [-1.9937385 ]
 [-0.5694002 ]
 [-1.4148034 ]
 [-1.2094983 ]
 [ 0.05776179]
 [ 0.04258299]]
556 Cost:  5.2886305 
Prediction:
 [[-2.394056  ]
 [-3.2151735 ]
 [-1.9936512 ]
 [-0.56933403]
 [-1.4147236 ]
 [-1.2094216 ]
 [ 0.05781054]
 [ 0.04263067]]
557 Cost:  5.2882833 
Prediction:
 [[-2.3939452 ]
 [-3.2150674 ]
 [-1.9935638 ]
 [-0.56926787]
 [-1.4146439 ]
 [-1.2093447 ]
 [ 0.05785942]
 [ 0.04267836]]
558 Cost:  5.287937 
Prediction:
 [[-2.3938346 ]
 [-3.214961  ]
 [-1.9934764 ]
 [-0.56920147]
 [-1.4145641 ]
 [-1.2092681 ]
 [ 0.05790818]
 [ 0.04272604]]
559 Cost:  5.287591 
Prediction:
 [[-2.393724  ]
 [-3.2148552 ]
 [-1.993389  ]
 [-0.5691354 ]
 [-1.4144846 ]
 [-1.2091912 ]
 [ 0.05795705]
 [ 0.04277372]]
560 Cost:  5.287245 
Prediction:
 [[-2.3936133 ]
 [-3.214749  ]
 [-1.9933016 ]
 [-0.56906915]
 [-1.4144049 ]
 [-1.2091146 ]
 [ 0.05800581]
 [ 0.04282135]]
561 Cost:  5.2868977 
Prediction:
 [[-2.3935027 ]
 [-3.2146425 ]
 [

681 Cost:  5.2454863 
Prediction:
 [[-2.3802462 ]
 [-3.2019224 ]
 [-1.9827447 ]
 [-0.5610719 ]
 [-1.404778  ]
 [-1.1998439 ]
 [ 0.06389987]
 [ 0.04857898]]
682 Cost:  5.2451425 
Prediction:
 [[-2.380136  ]
 [-3.2018166 ]
 [-1.9826576 ]
 [-0.56100607]
 [-1.4046985 ]
 [-1.1997672 ]
 [ 0.06394839]
 [ 0.04862636]]
683 Cost:  5.2447996 
Prediction:
 [[-2.3800259 ]
 [-3.201711  ]
 [-1.9825706 ]
 [-0.56094015]
 [-1.4046192 ]
 [-1.199691  ]
 [ 0.06399691]
 [ 0.04867381]]
684 Cost:  5.2444553 
Prediction:
 [[-2.3799157 ]
 [-3.2016048 ]
 [-1.9824835 ]
 [-0.56087434]
 [-1.40454   ]
 [-1.1996146 ]
 [ 0.06404549]
 [ 0.04872119]]
685 Cost:  5.244112 
Prediction:
 [[-2.3798056 ]
 [-3.201499  ]
 [-1.9823966 ]
 [-0.5608084 ]
 [-1.4044604 ]
 [-1.1995382 ]
 [ 0.06409407]
 [ 0.0487687 ]]
686 Cost:  5.2437687 
Prediction:
 [[-2.379695  ]
 [-3.2013936 ]
 [-1.9823095 ]
 [-0.5607425 ]
 [-1.4043812 ]
 [-1.1994618 ]
 [ 0.06414258]
 [ 0.04881608]]
687 Cost:  5.2434254 
Prediction:
 [[-2.379585  ]
 [-3.2012875 ]


745 Cost:  5.2235527 
Prediction:
 [[-2.3732018 ]
 [-3.19516   ]
 [-1.97718   ]
 [-0.5568578 ]
 [-1.3997045 ]
 [-1.194958  ]
 [ 0.06700563]
 [ 0.05161363]]
746 Cost:  5.2232113 
Prediction:
 [[-2.3730917 ]
 [-3.1950545 ]
 [-1.9770931 ]
 [-0.5567919 ]
 [-1.3996252 ]
 [-1.1948818 ]
 [ 0.06705409]
 [ 0.05166101]]
747 Cost:  5.222869 
Prediction:
 [[-2.3729818 ]
 [-3.194949  ]
 [-1.9770062 ]
 [-0.5567262 ]
 [-1.3995459 ]
 [-1.1948054 ]
 [ 0.06710261]
 [ 0.05170834]]
748 Cost:  5.2225275 
Prediction:
 [[-2.3728719 ]
 [-3.1948438 ]
 [-1.9769195 ]
 [-0.5566603 ]
 [-1.3994666 ]
 [-1.1947292 ]
 [ 0.06715119]
 [ 0.05175567]]
749 Cost:  5.222185 
Prediction:
 [[-2.3727617 ]
 [-3.194738  ]
 [-1.9768326 ]
 [-0.5565946 ]
 [-1.3993874 ]
 [-1.1946528 ]
 [ 0.06719959]
 [ 0.05180311]]
750 Cost:  5.221843 
Prediction:
 [[-2.3726516 ]
 [-3.1946325 ]
 [-1.9767455 ]
 [-0.5565287 ]
 [-1.3993083 ]
 [-1.1945766 ]
 [ 0.06724811]
 [ 0.05185044]]
751 Cost:  5.2215014 
Prediction:
 [[-2.3725417 ]
 [-3.194527  ]
 [

849 Cost:  5.1881447 
Prediction:
 [[-2.3617892 ]
 [-3.1842113 ]
 [-1.9681691 ]
 [-0.55003273]
 [-1.3914872 ]
 [-1.1870452 ]
 [ 0.07203388]
 [ 0.05652493]]
850 Cost:  5.187805 
Prediction:
 [[-2.3616798 ]
 [-3.1841056 ]
 [-1.9680824 ]
 [-0.5499673 ]
 [-1.3914087 ]
 [-1.1869695 ]
 [ 0.07208216]
 [ 0.05657208]]
851 Cost:  5.1874657 
Prediction:
 [[-2.3615704 ]
 [-3.1840005 ]
 [-1.967996  ]
 [-0.54990184]
 [-1.3913296 ]
 [-1.1868936 ]
 [ 0.07213032]
 [ 0.05661923]]
852 Cost:  5.187126 
Prediction:
 [[-2.3614607 ]
 [-3.1838956 ]
 [-1.9679096 ]
 [-0.5498364 ]
 [-1.3912506 ]
 [-1.1868176 ]
 [ 0.0721786 ]
 [ 0.05666631]]
853 Cost:  5.1867876 
Prediction:
 [[-2.3613515 ]
 [-3.1837907 ]
 [-1.9678231 ]
 [-0.54977083]
 [-1.3911718 ]
 [-1.1867417 ]
 [ 0.07222676]
 [ 0.05671346]]
854 Cost:  5.186449 
Prediction:
 [[-2.361242  ]
 [-3.1836855 ]
 [-1.9677367 ]
 [-0.5497055 ]
 [-1.3910933 ]
 [-1.1866658 ]
 [ 0.07227504]
 [ 0.05676055]]
855 Cost:  5.1861095 
Prediction:
 [[-2.3611326 ]
 [-3.1835804 ]
 [

 [ 0.06015033]]
927 Cost:  5.161762 
Prediction:
 [[-2.353259  ]
 [-3.1760225 ]
 [-1.9614316 ]
 [-0.5449313 ]
 [-1.3853446 ]
 [-1.18113   ]
 [ 0.07579237]
 [ 0.06019729]]
928 Cost:  5.1614256 
Prediction:
 [[-2.35315   ]
 [-3.175918  ]
 [-1.9613453 ]
 [-0.5448662 ]
 [-1.385266  ]
 [-1.1810545 ]
 [ 0.07584047]
 [ 0.06024432]]
929 Cost:  5.1610875 
Prediction:
 [[-2.3530407 ]
 [-3.1758127 ]
 [-1.961259  ]
 [-0.5448009 ]
 [-1.3851873 ]
 [-1.1809787 ]
 [ 0.07588851]
 [ 0.06029135]]
930 Cost:  5.160751 
Prediction:
 [[-2.3529315 ]
 [-3.1757083 ]
 [-1.9611729 ]
 [-0.54473555]
 [-1.3851088 ]
 [-1.1809028 ]
 [ 0.07593668]
 [ 0.06033832]]
931 Cost:  5.1604137 
Prediction:
 [[-2.3528223 ]
 [-3.1756034 ]
 [-1.9610869 ]
 [-0.54467034]
 [-1.3850302 ]
 [-1.1808273 ]
 [ 0.07598466]
 [ 0.06038529]]
932 Cost:  5.160077 
Prediction:
 [[-2.352713  ]
 [-3.175499  ]
 [-1.9610006 ]
 [-0.544605  ]
 [-1.3849517 ]
 [-1.1807517 ]
 [ 0.07603282]
 [ 0.06043226]]
933 Cost:  5.1597395 
Prediction:
 [[-2.352604  ]
 

1051 Cost:  5.1201496 
Prediction:
 [[-2.339748  ]
 [-3.1630607 ]
 [-1.950765  ]
 [-0.5368537 ]
 [-1.3756186 ]
 [-1.1717643 ]
 [ 0.08174193]
 [ 0.06600827]]
1052 Cost:  5.119816 
Prediction:
 [[-2.3396392 ]
 [-3.1629567 ]
 [-1.9506793 ]
 [-0.5367887 ]
 [-1.3755403 ]
 [-1.171689  ]
 [ 0.08178985]
 [ 0.06605506]]
1053 Cost:  5.119482 
Prediction:
 [[-2.3395305 ]
 [-3.1628523 ]
 [-1.9505934 ]
 [-0.53672373]
 [-1.3754619 ]
 [-1.1716138 ]
 [ 0.08183777]
 [ 0.06610185]]
1054 Cost:  5.1191483 
Prediction:
 [[-2.339422  ]
 [-3.162748  ]
 [-1.9505074 ]
 [-0.53665864]
 [-1.3753836 ]
 [-1.1715381 ]
 [ 0.08188564]
 [ 0.06614864]]
1055 Cost:  5.1188145 
Prediction:
 [[-2.339313  ]
 [-3.162644  ]
 [-1.9504217 ]
 [-0.53659356]
 [-1.3753055 ]
 [-1.1714629 ]
 [ 0.0819335 ]
 [ 0.06619549]]
1056 Cost:  5.1184797 
Prediction:
 [[-2.3392043 ]
 [-3.1625395 ]
 [-1.9503357 ]
 [-0.5365286 ]
 [-1.375227  ]
 [-1.1713874 ]
 [ 0.08198142]
 [ 0.06624228]]
1057 Cost:  5.118145 
Prediction:
 [[-2.3390956 ]
 [-3.16243

 [ 0.06951064]]
1127 Cost:  5.09483 
Prediction:
 [[-2.3314972 ]
 [-3.1551418 ]
 [-1.94425   ]
 [-0.53192174]
 [-1.3696789 ]
 [-1.1660446 ]
 [ 0.0853743 ]
 [ 0.06955731]]
1128 Cost:  5.0944977 
Prediction:
 [[-2.331389  ]
 [-3.1550379 ]
 [-1.9441644 ]
 [-0.5318569 ]
 [-1.3696007 ]
 [-1.1659695 ]
 [ 0.08542204]
 [ 0.06960398]]
1129 Cost:  5.094166 
Prediction:
 [[-2.3312802 ]
 [-3.154934  ]
 [-1.9440786 ]
 [-0.53179204]
 [-1.3695225 ]
 [-1.1658944 ]
 [ 0.08546984]
 [ 0.06965059]]
1130 Cost:  5.093833 
Prediction:
 [[-2.331172  ]
 [-3.1548295 ]
 [-1.9439932 ]
 [-0.5317272 ]
 [-1.3694445 ]
 [-1.1658193 ]
 [ 0.08551753]
 [ 0.0696972 ]]
1131 Cost:  5.093502 
Prediction:
 [[-2.3310637 ]
 [-3.154726  ]
 [-1.9439076 ]
 [-0.53166234]
 [-1.3693665 ]
 [-1.165744  ]
 [ 0.08556521]
 [ 0.06974381]]
1132 Cost:  5.093169 
Prediction:
 [[-2.330955  ]
 [-3.1546216 ]
 [-1.943822  ]
 [-0.5315976 ]
 [-1.3692886 ]
 [-1.1656688 ]
 [ 0.08561301]
 [ 0.06979042]]
1133 Cost:  5.092838 
Prediction:
 [[-2.3308468 

1217 Cost:  5.0650473 
Prediction:
 [[-2.3217587 ]
 [-3.1458    ]
 [-1.9365629 ]
 [-0.5261009 ]
 [-1.3626698 ]
 [-1.1592952 ]
 [ 0.08966041]
 [ 0.07374322]]
1218 Cost:  5.0647163 
Prediction:
 [[-2.3216503 ]
 [-3.1456964 ]
 [-1.9364774 ]
 [-0.52603626]
 [-1.362592  ]
 [-1.1592205 ]
 [ 0.08970797]
 [ 0.07378972]]
1219 Cost:  5.0643864 
Prediction:
 [[-2.3215423 ]
 [-3.1455927 ]
 [-1.9363922 ]
 [-0.52597153]
 [-1.3625141 ]
 [-1.1591455 ]
 [ 0.08975559]
 [ 0.07383621]]
1220 Cost:  5.0640564 
Prediction:
 [[-2.321434  ]
 [-3.1454887 ]
 [-1.9363071 ]
 [-0.52590716]
 [-1.3624364 ]
 [-1.1590706 ]
 [ 0.08980298]
 [ 0.07388258]]
1221 Cost:  5.0637264 
Prediction:
 [[-2.3213263 ]
 [-3.1453853 ]
 [-1.9362217 ]
 [-0.52584255]
 [-1.3623587 ]
 [-1.1589957 ]
 [ 0.08985054]
 [ 0.07392895]]
1222 Cost:  5.0633984 
Prediction:
 [[-2.3212185 ]
 [-3.1452823 ]
 [-1.9361366 ]
 [-0.5257782 ]
 [-1.362281  ]
 [-1.1589209 ]
 [ 0.08989799]
 [ 0.07397532]]
1223 Cost:  5.063068 
Prediction:
 [[-2.3211102 ]
 [-3.145

1321 Cost:  5.0308733 
Prediction:
 [[-2.310545  ]
 [-3.1350393 ]
 [-1.9277098 ]
 [-0.5194001 ]
 [-1.354599  ]
 [-1.1515238 ]
 [ 0.09459376]
 [ 0.0785628 ]]
1322 Cost:  5.030545 
Prediction:
 [[-2.3104372 ]
 [-3.1349359 ]
 [-1.9276248 ]
 [-0.51933587]
 [-1.3545214 ]
 [-1.1514493 ]
 [ 0.09464109]
 [ 0.07860905]]
1323 Cost:  5.0302186 
Prediction:
 [[-2.3103297 ]
 [-3.1348326 ]
 [-1.9275401 ]
 [-0.5192716 ]
 [-1.3544443 ]
 [-1.1513748 ]
 [ 0.09468842]
 [ 0.0786553 ]]
1324 Cost:  5.029891 
Prediction:
 [[-2.3102221 ]
 [-3.1347294 ]
 [-1.9274551 ]
 [-0.51920736]
 [-1.3543667 ]
 [-1.1513003 ]
 [ 0.09473574]
 [ 0.07870156]]
1325 Cost:  5.029564 
Prediction:
 [[-2.3101149 ]
 [-3.134626  ]
 [-1.9273701 ]
 [-0.5191431 ]
 [-1.3542893 ]
 [-1.1512256 ]
 [ 0.09478307]
 [ 0.07874775]]
1326 Cost:  5.0292373 
Prediction:
 [[-2.310007  ]
 [-3.134523  ]
 [-1.9272853 ]
 [-0.51907885]
 [-1.3542119 ]
 [-1.1511513 ]
 [ 0.09483039]
 [ 0.07879394]]
1327 Cost:  5.0289106 
Prediction:
 [[-2.3098996 ]
 [-3.13441

1421 Cost:  4.99827 
Prediction:
 [[-2.2998018 ]
 [-3.1247354 ]
 [-1.9192325 ]
 [-0.51298237]
 [-1.3468693 ]
 [-1.1440812 ]
 [ 0.09931731]
 [ 0.08317542]]
1422 Cost:  4.997945 
Prediction:
 [[-2.2996945 ]
 [-3.1246324 ]
 [-1.9191478 ]
 [-0.51291823]
 [-1.3467921 ]
 [-1.1440068 ]
 [ 0.09936452]
 [ 0.08322144]]
1423 Cost:  4.9976206 
Prediction:
 [[-2.2995872 ]
 [-3.1245298 ]
 [-1.9190632 ]
 [-0.5128542 ]
 [-1.3467151 ]
 [-1.1439325 ]
 [ 0.09941173]
 [ 0.08326751]]
1424 Cost:  4.9972963 
Prediction:
 [[-2.2994804 ]
 [-3.1244268 ]
 [-1.9189786 ]
 [-0.5127901 ]
 [-1.3466381 ]
 [-1.1438583 ]
 [ 0.09945881]
 [ 0.08331358]]
1425 Cost:  4.9969707 
Prediction:
 [[-2.2993727 ]
 [-3.1243238 ]
 [-1.9188939 ]
 [-0.51272607]
 [-1.3465606 ]
 [-1.1437839 ]
 [ 0.09950596]
 [ 0.0833596 ]]
1426 Cost:  4.996646 
Prediction:
 [[-2.2992659 ]
 [-3.1242208 ]
 [-1.9188093 ]
 [-0.51266205]
 [-1.3464836 ]
 [-1.1437098 ]
 [ 0.09955311]
 [ 0.08340567]]
1427 Cost:  4.996321 
Prediction:
 [[-2.2991586 ]
 [-3.1241179

1533 Cost:  4.962039 
Prediction:
 [[-2.287818  ]
 [-3.113236  ]
 [-1.909773  ]
 [-0.50582325]
 [-1.3382457 ]
 [-1.1357774 ]
 [ 0.10458684]
 [ 0.0883233 ]]
1534 Cost:  4.961717 
Prediction:
 [[-2.2877111 ]
 [-3.1131337 ]
 [-1.9096887 ]
 [-0.50575936]
 [-1.3381689 ]
 [-1.1357033 ]
 [ 0.10463393]
 [ 0.08836913]]
1535 Cost:  4.9613943 
Prediction:
 [[-2.2876043 ]
 [-3.113031  ]
 [-1.9096042 ]
 [-0.50569546]
 [-1.338092  ]
 [-1.1356293 ]
 [ 0.1046809 ]
 [ 0.08841503]]
1536 Cost:  4.9610724 
Prediction:
 [[-2.2874975 ]
 [-3.1129284 ]
 [-1.90952   ]
 [-0.5056318 ]
 [-1.3380152 ]
 [-1.1355554 ]
 [ 0.10472775]
 [ 0.08846074]]
1537 Cost:  4.9607506 
Prediction:
 [[-2.2873907 ]
 [-3.1128263 ]
 [-1.9094359 ]
 [-0.505568  ]
 [-1.3379384 ]
 [-1.1354815 ]
 [ 0.10477459]
 [ 0.08850652]]
1538 Cost:  4.960429 
Prediction:
 [[-2.287284  ]
 [-3.1127238 ]
 [-1.909352  ]
 [-0.50550425]
 [-1.3378617 ]
 [-1.1354076 ]
 [ 0.10482144]
 [ 0.08855224]]
1539 Cost:  4.960107 
Prediction:
 [[-2.287177  ]
 [-3.112621

1623 Cost:  4.933161 
Prediction:
 [[-2.2782266 ]
 [-3.104037  ]
 [-1.9022052 ]
 [-0.500095  ]
 [-1.331346  ]
 [-1.1291339 ]
 [ 0.10880184]
 [ 0.09243935]]
1624 Cost:  4.932841 
Prediction:
 [[-2.2781205 ]
 [-3.1039348 ]
 [-1.9021212 ]
 [-0.5000316 ]
 [-1.3312696 ]
 [-1.1290601 ]
 [ 0.10884851]
 [ 0.09248495]]
1625 Cost:  4.932522 
Prediction:
 [[-2.278014  ]
 [-3.1038332 ]
 [-1.9020371 ]
 [-0.49996805]
 [-1.331193  ]
 [-1.1289866 ]
 [ 0.10889518]
 [ 0.09253061]]
1626 Cost:  4.9322014 
Prediction:
 [[-2.2779074 ]
 [-3.1037307 ]
 [-1.9019533 ]
 [-0.4999045 ]
 [-1.3311166 ]
 [-1.1289128 ]
 [ 0.10894191]
 [ 0.09257621]]
1627 Cost:  4.9318824 
Prediction:
 [[-2.2778013 ]
 [-3.1036289 ]
 [-1.9018693 ]
 [-0.49984097]
 [-1.3310401 ]
 [-1.1288393 ]
 [ 0.10898864]
 [ 0.09262186]]
1628 Cost:  4.931563 
Prediction:
 [[-2.2776952 ]
 [-3.103527  ]
 [-1.9017855 ]
 [-0.49977744]
 [-1.3309635 ]
 [-1.1287655 ]
 [ 0.10903531]
 [ 0.09266746]]
1629 Cost:  4.931243 
Prediction:
 [[-2.2775886 ]
 [-3.103425 

1746 Cost:  4.893995 
Prediction:
 [[-2.2651677 ]
 [-3.091508  ]
 [-1.8918997 ]
 [-0.49229753]
 [-1.321952  ]
 [-1.1200885 ]
 [ 0.11453855]
 [ 0.09804285]]
1747 Cost:  4.8936787 
Prediction:
 [[-2.2650619 ]
 [-3.0914068 ]
 [-1.8918163 ]
 [-0.49223435]
 [-1.3218759 ]
 [-1.1200153 ]
 [ 0.1145851 ]
 [ 0.09808832]]
1748 Cost:  4.8933616 
Prediction:
 [[-2.264956  ]
 [-3.0913048 ]
 [-1.8917328 ]
 [-0.49217093]
 [-1.3217999 ]
 [-1.1199418 ]
 [ 0.11463159]
 [ 0.09813374]]
1749 Cost:  4.8930454 
Prediction:
 [[-2.2648501 ]
 [-3.0912037 ]
 [-1.8916491 ]
 [-0.49210775]
 [-1.3217236 ]
 [-1.1198684 ]
 [ 0.11467814]
 [ 0.09817916]]
1750 Cost:  4.8927274 
Prediction:
 [[-2.2647438 ]
 [-3.0911016 ]
 [-1.8915654 ]
 [-0.49204457]
 [-1.3216473 ]
 [-1.119795  ]
 [ 0.1147247 ]
 [ 0.09822464]]
1751 Cost:  4.892412 
Prediction:
 [[-2.2646384 ]
 [-3.0910006 ]
 [-1.8914822 ]
 [-0.49198127]
 [-1.3215712 ]
 [-1.1197218 ]
 [ 0.11477119]
 [ 0.09827   ]]
1752 Cost:  4.892094 
Prediction:
 [[-2.264532  ]
 [-3.09089

1842 Cost:  4.863673 
Prediction:
 [[-2.2550125 ]
 [-3.0817695 ]
 [-1.8838893 ]
 [-0.48623574]
 [-1.314649  ]
 [-1.1130568 ]
 [ 0.11899686]
 [ 0.10239595]]
1843 Cost:  4.8633595 
Prediction:
 [[-2.2549071 ]
 [-3.0816684 ]
 [-1.8838062 ]
 [-0.4861728 ]
 [-1.314573  ]
 [-1.112984  ]
 [ 0.11904329]
 [ 0.10244119]]
1844 Cost:  4.8630447 
Prediction:
 [[-2.2548018 ]
 [-3.0815673 ]
 [-1.8837227 ]
 [-0.48610973]
 [-1.3144974 ]
 [-1.1129109 ]
 [ 0.11908966]
 [ 0.10248649]]
1845 Cost:  4.8627305 
Prediction:
 [[-2.2546961 ]
 [-3.081466  ]
 [-1.8836396 ]
 [-0.4860468 ]
 [-1.3144214 ]
 [-1.1128378 ]
 [ 0.11913598]
 [ 0.10253185]]
1846 Cost:  4.8624153 
Prediction:
 [[-2.2545905 ]
 [-3.0813646 ]
 [-1.8835562 ]
 [-0.48598373]
 [-1.3143455 ]
 [-1.1127645 ]
 [ 0.11918235]
 [ 0.10257715]]
1847 Cost:  4.862101 
Prediction:
 [[-2.2544851 ]
 [-3.0812635 ]
 [-1.8834729 ]
 [-0.48592067]
 [-1.3142695 ]
 [-1.1126916 ]
 [ 0.11922878]
 [ 0.10262245]]
1848 Cost:  4.861787 
Prediction:
 [[-2.2543797 ]
 [-3.08116

 [ 0.10583144]]
1919 Cost:  4.8395243 
Prediction:
 [[-2.246901  ]
 [-3.0739856 ]
 [-1.8774875 ]
 [-0.48139298]
 [-1.3088142 ]
 [-1.1074384 ]
 [ 0.12255937]
 [ 0.10587656]]
1920 Cost:  4.83921 
Prediction:
 [[-2.2467957 ]
 [-3.073884  ]
 [-1.8774043 ]
 [-0.48133004]
 [-1.3087384 ]
 [-1.1073657 ]
 [ 0.12260562]
 [ 0.1059218 ]]
1921 Cost:  4.8388977 
Prediction:
 [[-2.2466903 ]
 [-3.0737834 ]
 [-1.8773214 ]
 [-0.48126733]
 [-1.3086625 ]
 [-1.1072928 ]
 [ 0.12265193]
 [ 0.10596699]]
1922 Cost:  4.838585 
Prediction:
 [[-2.246585  ]
 [-3.0736823 ]
 [-1.8772384 ]
 [-0.4812044 ]
 [-1.3085867 ]
 [-1.1072198 ]
 [ 0.12269813]
 [ 0.10601217]]
1923 Cost:  4.8382716 
Prediction:
 [[-2.2464795 ]
 [-3.0735812 ]
 [-1.8771552 ]
 [-0.48114145]
 [-1.3085109 ]
 [-1.1071469 ]
 [ 0.12274438]
 [ 0.10605735]]
1924 Cost:  4.837959 
Prediction:
 [[-2.2463746 ]
 [-3.0734806 ]
 [-1.877072  ]
 [-0.48107874]
 [-1.3084351 ]
 [-1.1070739 ]
 [ 0.12279058]
 [ 0.10610253]]
1925 Cost:  4.8376455 
Prediction:
 [[-2.24626

2000 Cost:  4.8142614 
Prediction:
 [[-2.238386  ]
 [-3.065821  ]
 [-1.8707721 ]
 [-0.47631192]
 [-1.3026919 ]
 [-1.1015441 ]
 [ 0.12629521]
 [ 0.10952383]]
