In [1]:
import tensorflow.compat.v1 as tf

In [5]:
# x와 y 데이터 나열
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#feed_dict로 값 받기 위해
tf.disable_v2_behavior()
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b 

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val)

0 cost:  44581.117 
Prediction:
 [-31.868382 -43.030422 -39.640354 -46.502613 -31.351475]
10 cost:  6.09613 
Prediction:
 [154.89125 181.45663 181.54227 194.36116 139.87833]
20 cost:  5.663522 
Prediction:
 [155.44795 182.14156 182.20885 195.08853 140.40352]
30 cost:  5.639122 
Prediction:
 [155.44127 182.14932 182.20824 195.08931 140.41216]
40 cost:  5.6148477 
Prediction:
 [155.43289 182.15501 182.20563 195.08792 140.41922]
50 cost:  5.5906653 
Prediction:
 [155.42453 182.16069 182.20297 195.0865  140.42625]
60 cost:  5.5666695 
Prediction:
 [155.4162  182.16635 182.20038 195.08508 140.43327]
70 cost:  5.542771 
Prediction:
 [155.40788 182.172   182.19777 195.0837  140.44026]
80 cost:  5.518959 
Prediction:
 [155.3996  182.17764 182.19514 195.08229 140.44727]
90 cost:  5.49535 
Prediction:
 [155.39133 182.18324 182.19257 195.08092 140.45421]
100 cost:  5.471797 
Prediction:
 [155.38307 182.18886 182.18996 195.0795  140.46115]
110 cost:  5.448424 
Prediction:
 [155.37486 182.19443 182

1020 cost:  3.7634392 
Prediction:
 [154.71043 182.6455  181.97812 194.97067 141.02298]
1030 cost:  3.749062 
Prediction:
 [154.704   182.64987 181.97609 194.96968 141.02834]
1040 cost:  3.7347138 
Prediction:
 [154.69754 182.65424 181.97404 194.9687  141.03366]
1050 cost:  3.7204933 
Prediction:
 [154.69115 182.6586  181.97202 194.96771 141.03897]
1060 cost:  3.7063441 
Prediction:
 [154.68475 182.66293 181.96999 194.96672 141.04427]
1070 cost:  3.6922398 
Prediction:
 [154.67834 182.66727 181.96797 194.96573 141.04953]
1080 cost:  3.6782265 
Prediction:
 [154.67197 182.67157 181.96596 194.96475 141.0548 ]
1090 cost:  3.6642907 
Prediction:
 [154.66563 182.67589 181.96396 194.96379 141.06006]
1100 cost:  3.6504219 
Prediction:
 [154.65927 182.68015 181.96193 194.9628  141.06528]
1110 cost:  3.6366131 
Prediction:
 [154.65295 182.68445 181.95993 194.96182 141.0705 ]
1120 cost:  3.6228995 
Prediction:
 [154.64667 182.68872 181.95795 194.96088 141.07571]
1130 cost:  3.6092522 
Prediction

1990 cost:  2.665688 
Prediction:
 [154.15697 183.02031 181.80258 194.88953 141.47626]
2000 cost:  2.6570141 
Prediction:
 [154.15195 183.02368 181.80098 194.88881 141.4803 ]


In [8]:
# X matrix와 Y matrix로 구현
x_data = [[73., 80., 75.], [93.,88.,93.],[89.,91.,90.], [96.,98.,100.],[73.,66.,70.]] #[5, 3] matrix
y_data = [[152.], [185.], [180.], [196.], [142.]]#[5, 1] matrix

#feed_dict로 값 받기 위해
tf.disable_v2_behavior()
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b 

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val)

0 cost:  36601.24 
Prediction:
 [[-11.5888605]
 [-23.979177 ]
 [-18.405977 ]
 [-20.068546 ]
 [-20.855831 ]]
10 cost:  26.161188 
Prediction:
 [[157.57166]
 [179.3758 ]
 [181.94412]
 [198.1095 ]
 [134.2604 ]]
20 cost:  25.690144 
Prediction:
 [[158.0642 ]
 [180.00433]
 [182.54445]
 [198.76505]
 [134.74742]]
30 cost:  25.554699 
Prediction:
 [[158.04646]
 [180.01945]
 [182.5404 ]
 [198.76245]
 [134.76653]]
40 cost:  25.419971 
Prediction:
 [[158.02722]
 [180.03268]
 [182.53455]
 [198.7579 ]
 [134.78416]]
50 cost:  25.285938 
Prediction:
 [[158.00804]
 [180.04588]
 [182.52873]
 [198.75334]
 [134.80177]]
60 cost:  25.15264 
Prediction:
 [[157.9889 ]
 [180.05904]
 [182.5229 ]
 [198.7488 ]
 [134.81932]]
70 cost:  25.02012 
Prediction:
 [[157.96982]
 [180.07213]
 [182.5171 ]
 [198.74423]
 [134.8368 ]]
80 cost:  24.888277 
Prediction:
 [[157.95079]
 [180.08522]
 [182.51132]
 [198.73973]
 [134.85426]]
90 cost:  24.757153 
Prediction:
 [[157.93182]
 [180.09827]
 [182.50555]
 [198.73521]
 [134.87

1080 cost:  14.732776 
Prediction:
 [[156.2879 ]
 [181.2286 ]
 [182.00607]
 [198.34079]
 [136.383  ]]
1090 cost:  14.656436 
Prediction:
 [[156.27345]
 [181.23853]
 [182.0017 ]
 [198.33728]
 [136.3963 ]]
1100 cost:  14.580501 
Prediction:
 [[156.25905]
 [181.24843]
 [181.99733]
 [198.33379]
 [136.40958]]
1110 cost:  14.504982 
Prediction:
 [[156.2447 ]
 [181.25833]
 [181.99298]
 [198.33032]
 [136.42282]]
1120 cost:  14.42984 
Prediction:
 [[156.23036]
 [181.26816]
 [181.98862]
 [198.32683]
 [136.43602]]
1130 cost:  14.355095 
Prediction:
 [[156.21608]
 [181.27798]
 [181.98428]
 [198.32336]
 [136.4492 ]]
1140 cost:  14.28081 
Prediction:
 [[156.20184]
 [181.28778]
 [181.97998]
 [198.31992]
 [136.46234]]
1150 cost:  14.206919 
Prediction:
 [[156.18765]
 [181.29755]
 [181.97568]
 [198.31647]
 [136.47545]]
1160 cost:  14.13338 
Prediction:
 [[156.17346]
 [181.3073 ]
 [181.97137]
 [198.31302]
 [136.4885 ]]
1170 cost:  14.060255 
Prediction:
 [[156.15935]
 [181.31702]
 [181.96709]
 [198.3096