In [2]:
import tensorflow.compat.v1 as tf
import numpy as np

In [6]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [10]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

tf.disable_v2_behavior()
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b 

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val)
        


(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 cost:  54511.688 
Prediction:
 [[-63.106133]
 [-81.35016 ]
 [-77.06006 ]
 [-85.70967 ]
 [-62.188515]
 [-49.744644]]
10 cost:  10.58863 
Prediction:
 [[154.52928]
 [180.32957]
 [180.72559]
 [195.02733]
 [137.41943]
 [ 97.41287]]
20 cost:  8.038898 
Prediction:
 [[155.98999]
 [182.10834]
 [182.46614]
 [196.92487]
 [138.78018]
 [ 98.42178]]
30 cost:  7.989159 
Prediction:
 [[155.98671 ]
 [182.1269  ]
 [182.47267 ]
 [196.93399 ]
 [138.79831 ]
 [ 98.440865]]
40 cost:  7.9398446 
Prediction:
 [[155.97354]
 [182.13351]
 [182.46744]
 [196.9303 ]
 [138.80728]
 [ 98.45321]]
50 cost:  7.890884 
Prediction:
 [[155.96036]
 [182.14003]
 [182.46219]
 [196.92653]
 [138.81618]
 [ 98.46546]]
60 cost:  7.842224 
Prediction:
 [[155.9472 ]
 [182.14653]
 [182.45694]
 [196.9228 ]
 [138.82504]
 [ 98.47767]]
70 cost:  7.7938943 
Predicti

740 cost:  5.1883373 
Prediction:
 [[155.14882]
 [182.54134]
 [182.13803]
 [196.69435]
 [139.36522]
 [ 99.21827]]
750 cost:  5.157558 
Prediction:
 [[155.13838 ]
 [182.54652 ]
 [182.13387 ]
 [196.69135 ]
 [139.3723  ]
 [ 99.227936]]
760 cost:  5.1269584 
Prediction:
 [[155.12796]
 [182.55167]
 [182.12971]
 [196.68834]
 [139.37938]
 [ 99.23758]]
770 cost:  5.0965743 
Prediction:
 [[155.1176  ]
 [182.55682 ]
 [182.12558 ]
 [196.68535 ]
 [139.38643 ]
 [ 99.247185]]
780 cost:  5.066397 
Prediction:
 [[155.10725]
 [182.56194]
 [182.12146]
 [196.68237]
 [139.39345]
 [ 99.25677]]
790 cost:  5.0364356 
Prediction:
 [[155.09695 ]
 [182.56705 ]
 [182.11736 ]
 [196.67941 ]
 [139.40044 ]
 [ 99.266304]]
800 cost:  5.0066476 
Prediction:
 [[155.08667]
 [182.57211]
 [182.11325]
 [196.67645]
 [139.40742]
 [ 99.2758 ]]
810 cost:  4.9770546 
Prediction:
 [[155.07643 ]
 [182.57718 ]
 [182.10916 ]
 [196.67351 ]
 [139.41438 ]
 [ 99.285286]]
820 cost:  4.947659 
Prediction:
 [[155.06622]
 [182.58224]
 [182.

1630 cost:  3.1112783 
Prediction:
 [[154.34297]
 [182.94086]
 [181.817  ]
 [196.46063]
 [139.9147 ]
 [ 99.96272]]
1640 cost:  3.094177 
Prediction:
 [[154.3352 ]
 [182.94472]
 [181.8139 ]
 [196.45834]
 [139.92004]
 [ 99.96988]]
1650 cost:  3.0772088 
Prediction:
 [[154.32747]
 [182.94858]
 [181.81085]
 [196.4561 ]
 [139.92537]
 [ 99.97701]]
1660 cost:  3.0603645 
Prediction:
 [[154.31975]
 [182.95241]
 [181.80777]
 [196.45383]
 [139.93063]
 [ 99.9841 ]]
1670 cost:  3.0436258 
Prediction:
 [[154.31206 ]
 [182.95622 ]
 [181.80473 ]
 [196.45157 ]
 [139.93591 ]
 [ 99.991196]]
1680 cost:  3.0269852 
Prediction:
 [[154.30438 ]
 [182.96002 ]
 [181.80167 ]
 [196.44933 ]
 [139.94116 ]
 [ 99.998245]]
1690 cost:  3.0104444 
Prediction:
 [[154.29675 ]
 [182.96382 ]
 [181.79863 ]
 [196.4471  ]
 [139.94643 ]
 [100.005295]]
1700 cost:  2.9940557 
Prediction:
 [[154.28915]
 [182.9676 ]
 [181.79561]
 [196.44485]
 [139.95163]
 [100.0123 ]]
1710 cost:  2.9777439 
Prediction:
 [[154.28157]
 [182.97139]
 

In [12]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))
print("Others score will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[173.83722]]
Others score will be  [[137.67178]
 [189.6509 ]]


In [21]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'],
                                                shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

tf.disable_v2_behavior()
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b 

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)       


0 cost:  65246.855 
Prediction:
 [[ -78.39346 ]
 [ -91.51532 ]
 [ -91.25214 ]
 [-103.02751 ]
 [ -66.145706]
 [ -54.144466]
 [ -78.39346 ]
 [ -91.51532 ]
 [ -91.25214 ]
 [-103.02751 ]]
10 cost:  3.7054124 
Prediction:
 [[143.39388]
 [100.32303]
 [150.12364]
 [183.19707]
 [179.39894]
 [191.71655]
 [143.39388]
 [100.32303]
 [150.12364]
 [183.19707]]
20 cost:  2.9148605 
Prediction:
 [[181.0044  ]
 [193.46515 ]
 [144.63327 ]
 [101.236374]
 [151.48128 ]
 [184.82391 ]
 [181.0044  ]
 [193.46515 ]
 [144.63327 ]
 [101.236374]]
30 cost:  2.2443678 
Prediction:
 [[151.48172]
 [184.81892]
 [181.00232]
 [193.4631 ]
 [144.62793]
 [101.23214]
 [151.48172]
 [184.81892]
 [181.00232]
 [193.4631 ]]
40 cost:  2.237658 
Prediction:
 [[144.7228  ]
 [101.301765]
 [151.59119 ]
 [184.94527 ]
 [181.12949 ]
 [193.60182 ]
 [144.7228  ]
 [101.301765]
 [151.59119 ]
 [184.94527 ]]
50 cost:  2.902204 
Prediction:
 [[181.01999 ]
 [193.48276 ]
 [144.63431 ]
 [101.236206]
 [151.50095 ]
 [184.83127 ]
 [181.01999 ]
 [193.

510 cost:  2.1103764 
Prediction:
 [[151.62201 ]
 [184.74644 ]
 [181.0543  ]
 [193.53157 ]
 [144.50266 ]
 [101.129364]
 [151.62201 ]
 [184.74644 ]
 [181.0543  ]
 [193.53157 ]]
520 cost:  2.0538473 
Prediction:
 [[144.59077]
 [101.19424]
 [151.72331]
 [184.86375]
 [181.17216]
 [193.66022]
 [144.59077]
 [101.19424]
 [151.72331]
 [184.86375]]
530 cost:  2.7111936 
Prediction:
 [[181.07042]
 [193.54968]
 [144.50877]
 [101.13363]
 [151.63931]
 [184.75807]
 [181.07042]
 [193.54968]
 [144.50877]
 [101.13363]]
540 cost:  2.1030273 
Prediction:
 [[151.63004]
 [184.74228]
 [181.05725]
 [193.53563]
 [144.49532]
 [101.12362]
 [151.63004]
 [184.74228]
 [181.05725]
 [193.53563]]
550 cost:  2.043795 
Prediction:
 [[144.58307]
 [101.18821]
 [151.7309 ]
 [184.85905]
 [181.17459]
 [193.66368]
 [144.58307]
 [101.18821]
 [151.7309 ]
 [184.85905]]
560 cost:  2.7005205 
Prediction:
 [[181.07327]
 [193.55362]
 [144.5014 ]
 [101.12788]
 [151.6472 ]
 [184.75381]
 [181.07327]
 [193.55362]
 [144.5014 ]
 [101.127

1000 cost:  1.9087279 
Prediction:
 [[144.47371]
 [101.10624]
 [151.83539]
 [184.79338]
 [181.2074 ]
 [193.71333]
 [144.47371]
 [101.10624]
 [151.83539]
 [184.79338]]
1010 cost:  2.5548418 
Prediction:
 [[181.1124  ]
 [193.6102  ]
 [144.3973  ]
 [101.049934]
 [151.75679 ]
 [184.69487 ]
 [181.1124  ]
 [193.6102  ]
 [144.3973  ]
 [101.049934]]
1020 cost:  1.9989593 
Prediction:
 [[151.74783]
 [184.68015]
 [181.0999 ]
 [193.59694]
 [144.38478]
 [101.04077]
 [151.74783]
 [184.68015]
 [181.0999 ]
 [193.59694]]
1030 cost:  1.9006662 
Prediction:
 [[144.46681 ]
 [101.101326]
 [151.84178 ]
 [184.78934 ]
 [181.2094  ]
 [193.7165  ]
 [144.46681 ]
 [101.101326]
 [151.84178 ]
 [184.78934 ]]
1040 cost:  2.5460062 
Prediction:
 [[181.11478]
 [193.6138 ]
 [144.39075]
 [101.04528]
 [151.7635 ]
 [184.69124]
 [181.11478]
 [193.6138 ]
 [144.39075]
 [101.04528]]
1050 cost:  1.9931797 
Prediction:
 [[151.75456]
 [184.67654]
 [181.10233]
 [193.60059]
 [144.37827]
 [101.03615]
 [151.75456]
 [184.67654]
 [181

1530 cost:  1.9103813 
Prediction:
 [[151.85345]
 [184.62321]
 [181.13719]
 [193.65587]
 [144.28029]
 [100.97004]
 [151.85345]
 [184.62321]
 [181.13719]
 [193.65587]]
1540 cost:  1.7790632 
Prediction:
 [[144.35712]
 [101.02692]
 [151.94113]
 [184.72545]
 [181.23952]
 [193.76772]
 [144.35712]
 [101.02692]
 [151.94113]
 [184.72545]]
1550 cost:  2.4097662 
Prediction:
 [[181.15112]
 [193.67181]
 [144.28625]
 [100.97484]
 [151.86786]
 [184.63402]
 [181.15112]
 [193.67181]
 [144.28625]
 [100.97484]]
1560 cost:  1.905721 
Prediction:
 [[151.8591 ]
 [184.62013]
 [181.13914]
 [193.65915]
 [144.27449]
 [100.96637]
 [151.8591 ]
 [184.62013]
 [181.13914]
 [193.65915]]
1570 cost:  1.7727289 
Prediction:
 [[144.35109]
 [101.02305]
 [151.94646]
 [184.72198]
 [181.24109]
 [193.77057]
 [144.35109]
 [101.02305]
 [151.94646]
 [184.72198]]
1580 cost:  2.4024487 
Prediction:
 [[181.15303]
 [193.67506]
 [144.28046]
 [100.97118]
 [151.87343]
 [184.6309 ]
 [181.15303]
 [193.67506]
 [144.28046]
 [100.97118]]